Change reference text quotes to chevrons
sillsdev/Glyssen pull request #722
Opened 2020-09-03 01:02 UTC by tombogle

2020-09-03 01:03 UTC, tombogle commented
I think we probably want to wait to merge this until FCBH has produced their version of the DG with chevrons and we have been able to compare the two.

2020-09-03 16:45 UTC, andrew-polk reviewed
I'll let you respond to some of these before I keep going.

> Reviewed 20 of 100 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/722#-:-MGJqrkz5EDwoSR3pZNn:beg3qq0)* status: 31 of 100 files reviewed, 23 unresolved discussions (waiting on @tombogle)

___
*[DistFiles/reference_texts/English/2PE.xml, line 188 at r1](https://reviewable.io/reviews/sillsdev/glyssen/722#-MGJlWNe0E71tj02M5fF:-MGJlWNfE5OaJ2_iXhmv:b-8gma7w) ([raw file](https://github.com/sillsdev/glyssen/blob/c41fcbdbe20206849c41b6ee3c04ed12c8524b21/DistFiles/reference_texts/English/2PE.xml#L188)):*
> ```
> ,.»
> ```
Not related to this change, but there's an extraneous period.
___
*[DistFiles/reference_texts/English/DAN.xml, line 1611 at r1](https://reviewable.io/reviews/sillsdev/glyssen/722#-MGJlsIw72WBvhElldaO:-MGJlsIw72WBvhElldaP:bbsdpe7) ([raw file](https://github.com/sillsdev/glyssen/blob/c41fcbdbe20206849c41b6ee3c04ed12c8524b21/DistFiles/reference_texts/English/DAN.xml#L1611)):*
> ```XML
>   </block>
>   <UnappliedSplits />
> </book>
> ```

Looks like most of the quotes in this book are not marked.
___
*[DistFiles/reference_texts/English/EST.xml, line 86 at r1](https://reviewable.io/reviews/sillsdev/glyssen/722#-MGJnMz_Dbhhv_wCkQln:-MGJnMz_Dbhhv_wCkQlo:bn5799x) ([raw file](https://github.com/sillsdev/glyssen/blob/c41fcbdbe20206849c41b6ee3c04ed12c8524b21/DistFiles/reference_texts/English/EST.xml#L86)):*
> ```
> small.
> ```
no close
___
*[DistFiles/reference_texts/English/en.ldml, line 26 at r1](https://reviewable.io/reviews/sillsdev/glyssen/722#-MGJnv2ACE4LUGl1plop:-MGJnv2ACE4LUGl1ploq:b-udygq6) ([raw file](https://github.com/sillsdev/glyssen/blob/c41fcbdbe20206849c41b6ee3c04ed12c8524b21/DistFiles/reference_texts/English/en.ldml#L26)):*
> ```
> 		</orientation>
> 	</layout>
> </ldml>
> ```

This seems an ironic time to add the correct ldml for the English reference text.
___
*[DistFiles/reference_texts/English/HAB.xml, line 130 at r1](https://reviewable.io/reviews/sillsdev/glyssen/722#-MGJoMAEE26eVaYkKpVs:-MGJoMAEE26eVaYkKpVt:bv4ls28) ([raw file](https://github.com/sillsdev/glyssen/blob/c41fcbdbe20206849c41b6ee3c04ed12c8524b21/DistFiles/reference_texts/English/HAB.xml#L130)):*
> ```
> iniquity!
> ```
no close.
It looks like at one point they had this for God throughv 20, so there is an extra close there and the quotes in 19 are marked second level.
___
*[DistFiles/reference_texts/English/HAG.xml, line 51 at r1](https://reviewable.io/reviews/sillsdev/glyssen/722#-MGJomZcA4nQG7l_WsVM:-MGJomZcA4nQG7l_WsVN:brvixvt) ([raw file](https://github.com/sillsdev/glyssen/blob/c41fcbdbe20206849c41b6ee3c04ed12c8524b21/DistFiles/reference_texts/English/HAG.xml#L51)):*
> ```
> You looked for much, and, behold, it came to little; and when you brought it home, I blew it away. Why?
> ```
missing quotes
Would it be worthwhile to try to algorithmically find places where there is no quote mark but we are starting a quote or vice versa for end?
Or will all these issues go away when they make the ref text match the WEB exactly (but now with guillemots)?
___
*[DistFiles/reference_texts/English/HAG.xml, line 228 at r1](https://reviewable.io/reviews/sillsdev/glyssen/722#-MGJpIM8-UFqwDMLavBa:-MGJpIM8-UFqwDMLavBb:bx4278c) ([raw file](https://github.com/sillsdev/glyssen/blob/c41fcbdbe20206849c41b6ee3c04ed12c8524b21/DistFiles/reference_texts/English/HAG.xml#L228)):*
> ```XML
>     <verse num="19" />
>     <text>Is the seed yet in the barn? Yes, the vine, the fig tree, the pomegranate, and the olive tree haven’t brought forth. From this day will I bless you.› »</text>
>   </block>
> ```

Quote marks for v14-19 don't match character. I guess that's ok?
___
*[DistFiles/reference_texts/English/OBA.xml, line 23 at r1](https://reviewable.io/reviews/sillsdev/glyssen/722#-MGJpn10A5YDhYh7bCuc:-MGJpn10A5YDhYh7bCud:b-imc97w) ([raw file](https://github.com/sillsdev/glyssen/blob/c41fcbdbe20206849c41b6ee3c04ed12c8524b21/DistFiles/reference_texts/English/OBA.xml#L23)):*
> ```XML
>     <verse num="2" />
>     <text>Behold, I have made you small among the nations. You are greatly despised.</text>
>   </block>
> ```

quote marks for v1-2 don't match character. Should they?
___
*[DistFiles/reference_texts/Russian/1JN.xml, line 131 at r1](https://reviewable.io/reviews/sillsdev/glyssen/722#-MGJqEvTCDQeZdsxiU7w:-MGJqEvTCDQeZdsxiU7x:bc6k46q) ([raw file](https://github.com/sillsdev/glyssen/blob/c41fcbdbe20206849c41b6ee3c04ed12c8524b21/DistFiles/reference_texts/Russian/1JN.xml#L131)):*
> ```
> 'я познал Его'
> ```
Not sure if you want to do anything about it, but this Russian "quote" is in straight single quotes.
___
*[DistFiles/reference_texts/Russian/1PE.xml, line 217 at r1](https://reviewable.io/reviews/sillsdev/glyssen/722#-MGJqVDv4LqDvpuL62UI:-MGJqVDw-rpmCHVUpTB5:b-e3zl2z) ([raw file](https://github.com/sillsdev/glyssen/blob/c41fcbdbe20206849c41b6ee3c04ed12c8524b21/DistFiles/reference_texts/Russian/1PE.xml#L217)):*
> ```
> но слово Господне пребывает вовек;»
> ```
Not sure how much we care, but this started with a dialogue dash, so it probably shouldn't end with a quote mark


<!-- Sent from Reviewable.io -->

2020-09-03 18:41 UTC, tombogle commented
It might have been after you left that we agreed not to try to mark up third level differently because it would entail a lot of manual work.  I know that the OT (especially) is likely to have lots of punctuation anomalies. I think my initial inclination would be to address any problems that pop up when comparing to FCBH's results. Then fix other problems in a separate PR (ideally getting them fixed in the DG). Otherwise, we're going to get even more out of sync.

2020-09-04 16:24 UTC, andrew-polk commented
Ok, so you want me to resolve all those issues I raised and just look for obvious errors in the conversion?

2020-09-04 16:50 UTC, andrew-polk approved these changes
Given that the goal is a simple codepoint for codepoint find and replace and then add spaces, I don't think I have much to contribute by way of review, so most of the files I didn't even look at.

I left my comments in place in case they are worth noting.

But I'm accepting the PR.

A few thoughts on spaces: 
- The additional spaces won't mess up the algorithm anywhere, will it? 
- You should consider non-breaking or even non-breaking small spaces.
- In French, anyway, there is usually space between the inner-most guillemets and the words. You may want to consider that, too.

> Reviewed 69 of 100 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/722#-:-MGOzWPrBMAZZ6cN1O9m:b-cjwe4o)* status: all files reviewed, 21 unresolved discussions (waiting on @tombogle)

___
*[DistFiles/reference_texts/English/EZK.xml, line 1125 at r1](https://reviewable.io/reviews/sillsdev/glyssen/722#-MGOxR8L7SXP_tlIbuaQ:-MGOxR8L7SXP_tlIbuaR:b-du0tlm) ([raw file](https://github.com/sillsdev/glyssen/blob/c41fcbdbe20206849c41b6ee3c04ed12c8524b21/DistFiles/reference_texts/English/EZK.xml#L1125)):*
> ```
> Israel;» › but tell them, ‹ «The
> ```
This can't be right.
___
*[DistFiles/reference_texts/English/EZK.xml, line 2923 at r1](https://reviewable.io/reviews/sillsdev/glyssen/722#-MGOxfr55FyAn5qB3aXq:-MGOxfr55FyAn5qB3aXr:b-ayvvv5) ([raw file](https://github.com/sillsdev/glyssen/blob/c41fcbdbe20206849c41b6ee3c04ed12c8524b21/DistFiles/reference_texts/English/EZK.xml#L2923)):*
> ```
> «The 
> ```
Double opener after double opener (in v20)


<!-- Sent from Reviewable.io -->

2020-09-09 13:07 UTC, tombogle commented
@andrew-polk Thanks for your review and feedback. We'll definitely want to look at the specific errors you called out once we get through the initial conversion, so for any that appear to be wrong in FCBH's DG, I'll turn them into cards in the appropriate Trello board ([OT](https://trello.com/b/pa1soiAu/glyssen-ot-reference-text-pg-1162) or [NT](https://trello.com/b/Y0y2UdvI/glyssen-nt-reference-text-pg-1215)). I have added your question about the non-breaking spaces to the FCBH meeting document. That thought had crossed my mind, but I know there are sometimes issues with font/rendering support, so I didn't dwell on it. However, since we use Charis for all the current reference texts in Glyssen, I think it should be supported. If so, I would favorthat, as it will almost certainly prevent some annoying line break issues.

2020-09-09 16:31 UTC, andrew-polk reviewed
> Reviewed 21 of 21 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/722)* status: all files reviewed, 21 unresolved discussions (waiting on @tombogle)

___
*[DistFiles/reference_texts/Russian/1CO.xml, line 106 at r2](https://reviewable.io/reviews/sillsdev/glyssen/722#-MGng9pF7n8ayl2chXHc:-MGng9pF7n8ayl2chXHd:b2b946f) ([raw file](https://github.com/sillsdev/glyssen/blob/f8b4b7786a36287cb8dbab625015c0d58f53ab43/DistFiles/reference_texts/Russian/1CO.xml#L106)):*
> ```XML
>     <ReferenceBlocks style="p" paragraphStart="true" chapter="1" initialStartVerse="12" characterId="narrator-1CO">
>       <verse num="12" />
>       <text>Now I mean this, that each one of you says, «I follow Paul,» «I follow Apollos,» «I follow Cephas,» and, «I follow Christ.»</text>
> ```

Did you mean to use narrow nobreak spaces here?
Doesn't seem appropriate. And the English file still has regular spaces.


<!-- Sent from Reviewable.io -->

2020-09-09 18:04 UTC, tombogle commented
___
*[GlyssenSharedTests/Resources/AzeriREVRefText.xml, line 2979 at r1](https://reviewable.io/reviews/sillsdev/glyssen/722#-MGJZLP64gCG8cYY_G9Z:-MGnxnjN3jVSy1O6t3yN:bsifygk) ([raw file](https://github.com/sillsdev/glyssen/blob/c41fcbdbe20206849c41b6ee3c04ed12c8524b21/GlyssenSharedTests/Resources/AzeriREVRefText.xml#L2979)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> tutmayacağam»
> ```
Likely it doesn't matter at all, but the rest of the Azeri uses less than and greater than.
</blockquote></details>

Yeah, I didn't figure it was necessarily worth changing anything that wasn't necessary and risk breaking some test that was expecting the old data.


<!-- Sent from Reviewable.io -->

2020-09-09 18:14 UTC, tombogle reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/722)* status: 94 of 100 files reviewed, 21 unresolved discussions (waiting on @andrew-polk)

___
*[DistFiles/reference_texts/English/1CH.xml, line 2330 at r1](https://reviewable.io/reviews/sillsdev/glyssen/722#-MGJVoDt3ReK6I8gOUkL:-MGo20Su12imJzKcy3Ej:bytlun) ([raw file](https://github.com/sillsdev/glyssen/blob/c41fcbdbe20206849c41b6ee3c04ed12c8524b21/DistFiles/reference_texts/English/1CH.xml#L2330)):*
> ignored
___
*[DistFiles/reference_texts/English/1CH.xml, line 2659 at r1](https://reviewable.io/reviews/sillsdev/glyssen/722#-MGJWfWX5SS0CFTDv7A0:-MGn7EDi6hEe8UQlV_fT:bxnwx2t) ([raw file](https://github.com/sillsdev/glyssen/blob/c41fcbdbe20206849c41b6ee3c04ed12c8524b21/DistFiles/reference_texts/English/1CH.xml#L2659)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> Go
> ```
Missing a start quote. Also, this is God, not narrator.
</blockquote></details>

https://trello.com/c/B1yo50tL/194-ich-2110-gods-quote-speaking-to-gad-is-not-broken-out-correctly-quotation-marks-are-incorrect-and-it-is-incorrectly-attributed-t
___
*[DistFiles/reference_texts/English/1CH.xml, line 2659 at r1](https://reviewable.io/reviews/sillsdev/glyssen/722#-MGJWoAv7IRiU8OyNvY_:-MGo2o9k3KoTaXuNeT1t:bkbvwkt) ([raw file](https://github.com/sillsdev/glyssen/blob/c41fcbdbe20206849c41b6ee3c04ed12c8524b21/DistFiles/reference_texts/English/1CH.xml#L2659)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> you.»
> ```
Missing second level close.
</blockquote></details>

https://trello.com/c/B1yo50tL/194-1ch-2110-gods-quote-speaking-to-gad-is-not-broken-out-correctly-quotation-marks-are-incorrect-and-it-is-incorrectly-attributed-t
___
*[DistFiles/reference_texts/English/2PE.xml, line 188 at r1](https://reviewable.io/reviews/sillsdev/glyssen/722#-MGJlWNe0E71tj02M5fF:-MGn8PaaDbgefScXrJlQ:b-w0xtvh) ([raw file](https://github.com/sillsdev/glyssen/blob/c41fcbdbe20206849c41b6ee3c04ed12c8524b21/DistFiles/reference_texts/English/2PE.xml#L188)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> ,.»
> ```
Not related to this change, but there's an extraneous period.
</blockquote></details>

https://trello.com/c/ZI1KkmWa/72-2pe-222-extraneous-period
___
*[DistFiles/reference_texts/English/DAN.xml, line 1611 at r1](https://reviewable.io/reviews/sillsdev/glyssen/722#-MGJlsIw72WBvhElldaO:-MGn9vNjEED5z4xRYbA_:b8beftk) ([raw file](https://github.com/sillsdev/glyssen/blob/c41fcbdbe20206849c41b6ee3c04ed12c8524b21/DistFiles/reference_texts/English/DAN.xml#L1611)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Looks like most of the quotes in this book are not marked.
</blockquote></details>

https://trello.com/c/vcPLTet1/195-dan-many-missing-quotation-marks
___
*[DistFiles/reference_texts/English/EST.xml, line 86 at r1](https://reviewable.io/reviews/sillsdev/glyssen/722#-MGJnMz_Dbhhv_wCkQln:-MGnANeuEsw-l8ZPgOCK:b1285oy) ([raw file](https://github.com/sillsdev/glyssen/blob/c41fcbdbe20206849c41b6ee3c04ed12c8524b21/DistFiles/reference_texts/English/EST.xml#L86)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> small.
> ```
no close
</blockquote></details>

https://trello.com/c/YJ5mICml/196-est-120-missing-closing-quotation-mark
___
*[DistFiles/reference_texts/English/EZK.xml, line 1125 at r1](https://reviewable.io/reviews/sillsdev/glyssen/722#-MGOxR8L7SXP_tlIbuaQ:-MGnBBXb-06xNAXYRj0d:b-d2ui0q) ([raw file](https://github.com/sillsdev/glyssen/blob/c41fcbdbe20206849c41b6ee3c04ed12c8524b21/DistFiles/reference_texts/English/EZK.xml#L1125)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> Israel;» › but tell them, ‹ «The
> ```
This can't be right.
</blockquote></details>

It looks weird, but I think it is correct. It matches the WEB. (However, all these quotation marks are missing in the DG https://trello.com/c/ylKiJ26Q/197-eze-1223-25-missing-quotation-marks-also-text-does-not-match-web) 
___
*[DistFiles/reference_texts/English/EZK.xml, line 2923 at r1](https://reviewable.io/reviews/sillsdev/glyssen/722#-MGOxfr55FyAn5qB3aXq:-MGnCrat3Z4YmFZHO4Md:b-p3f40q) ([raw file](https://github.com/sillsdev/glyssen/blob/c41fcbdbe20206849c41b6ee3c04ed12c8524b21/DistFiles/reference_texts/English/EZK.xml#L2923)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> «The 
> ```
Double opener after double opener (in v20)
</blockquote></details>

https://trello.com/c/5YB6JfBy/198-eze-2419-27-missing-quotation-marks-also-the-text-does-not-match-the-web
___
*[DistFiles/reference_texts/English/en.ldml, line 26 at r1](https://reviewable.io/reviews/sillsdev/glyssen/722#-MGJnv2ACE4LUGl1plop:-MGnDCUG7zLJnzRe0pOG:br409dw) ([raw file](https://github.com/sillsdev/glyssen/blob/c41fcbdbe20206849c41b6ee3c04ed12c8524b21/DistFiles/reference_texts/English/en.ldml#L26)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This seems an ironic time to add the correct ldml for the English reference text.
</blockquote></details>

My intention was to lay the groundwork for the possibility of swapping out the chevrons for the regular curly quotes (in the UI and/or when exporting).
___
*[DistFiles/reference_texts/English/HAB.xml, line 130 at r1](https://reviewable.io/reviews/sillsdev/glyssen/722#-MGJoMAEE26eVaYkKpVs:-MGnDzD1DVQDSOpXpLsE:bdkyo8) ([raw file](https://github.com/sillsdev/glyssen/blob/c41fcbdbe20206849c41b6ee3c04ed12c8524b21/DistFiles/reference_texts/English/HAB.xml#L130)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> iniquity!
> ```
no close.
It looks like at one point they had this for God throughv 20, so there is an extra close there and the quotes in 19 are marked second level.
</blockquote></details>

The quotation markup matches the WEB, so in that sense it s correct, even though FCBH decided to disagree. https://trello.com/c/ld7ti9IR/199-hab-212-20-gods-speech-ends-too-early
___
*[DistFiles/reference_texts/English/HAG.xml, line 51 at r1](https://reviewable.io/reviews/sillsdev/glyssen/722#-MGJomZcA4nQG7l_WsVM:-MGnHZrpEAGY3luSMzkQ:bcbxkvl) ([raw file](https://github.com/sillsdev/glyssen/blob/c41fcbdbe20206849c41b6ee3c04ed12c8524b21/DistFiles/reference_texts/English/HAG.xml#L51)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> You looked for much, and, behold, it came to little; and when you brought it home, I blew it away. Why?
> ```
missing quotes
Would it be worthwhile to try to algorithmically find places where there is no quote mark but we are starting a quote or vice versa for end?
Or will all these issues go away when they make the ref text match the WEB exactly (but now with guillemots)?
</blockquote></details>

I think I stopped trying to identify all of them because of FCBH's stated intention to try to resync with the WEB text. I do think we could probably try to find many of them algorithmically, but it's not super critical to the actual functioning of Glyssen. It's more of a potential speed bump for scripters though. https://trello.com/c/YsIbxJMc/200-hag-19-missing-quotation-marks
___
*[DistFiles/reference_texts/English/HAG.xml, line 228 at r1](https://reviewable.io/reviews/sillsdev/glyssen/722#-MGJpIM8-UFqwDMLavBa:-MGnIdAm1RFS1H9qjrVM:b-1i7zw5) ([raw file](https://github.com/sillsdev/glyssen/blob/c41fcbdbe20206849c41b6ee3c04ed12c8524b21/DistFiles/reference_texts/English/HAG.xml#L228)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Quote marks for v14-19 don't match character. I guess that's ok?
</blockquote></details>

https://trello.com/c/YC92Pcxe/201-hag-218-missing-second-level-opening-quotation-mark
https://trello.com/c/cwuNXo12/202-hag-214-second-level-opener-is-an-apostrophe-ie-closer-instead-of-opener
FCBH has talked about going back and redoing the whol [...]

2020-09-09 18:26 UTC, andrew-polk reviewed
> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/722)* status: all files reviewed, 5 unresolved discussions (waiting on @tombogle)

___
*[DistFiles/reference_texts/English/EXO.xml, line 4264 at r3](https://reviewable.io/reviews/sillsdev/glyssen/722#-MGo5Lou6ScgBl-xvPlt:-MGo5Lou6ScgBl-xvPlu:bfum0fk) ([raw file](https://github.com/sillsdev/glyssen/blob/a2c133541be4089200632dd1ece34400f62a0baa/DistFiles/reference_texts/English/EXO.xml#L4264)):*
> ```
> off:'
> ```
This one got missed.
___
*[DistFiles/reference_texts/English/EXO.xml, line 4379 at r3](https://reviewable.io/reviews/sillsdev/glyssen/722#-MGo5RXU3OQwxtwFU7bI:-MGo5RXU3OQwxtwFU7bJ:b-21o7db) ([raw file](https://github.com/sillsdev/glyssen/blob/a2c133541be4089200632dd1ece34400f62a0baa/DistFiles/reference_texts/English/EXO.xml#L4379)):*
> ```
> people:'
> ```
Another one missed.
Worth searching for this case?
___
*[DistFiles/reference_texts/Russian/LUK.xml, line 8127 at r3](https://reviewable.io/reviews/sillsdev/glyssen/722#-MGo5zSBCoqeg8xdhATA:-MGo5zSBCoqeg8xdhATB:bw678k1) ([raw file](https://github.com/sillsdev/glyssen/blob/a2c133541be4089200632dd1ece34400f62a0baa/DistFiles/reference_texts/Russian/LUK.xml#L8127)):*
> ```XML
>     <ReferenceBlocks style="p" paragraphStart="true" chapter="18" initialStartVerse="20" characterId="Jesus">
>       <verse num="20" />
>       <text>You know the commandments: ‹Don’t commit adultery,› ‹Don’t murder,› ‹Don’t steal,› ‹Don’t give false testimony,› ‹Honor your father and your mother.› »</text>
> ```

Was this intended? I didn't think you were doing this yet. 
And now I think it doesn't match the English file.
___
*[DistFiles/reference_texts/Russian/MAT.xml, line 6300 at r3](https://reviewable.io/reviews/sillsdev/glyssen/722#-MGo5v2V9_4KFeFriQDN:-MGo5v2V9_4KFeFriQDO:bw678k1) ([raw file](https://github.com/sillsdev/glyssen/blob/a2c133541be4089200632dd1ece34400f62a0baa/DistFiles/reference_texts/Russian/MAT.xml#L6300)):*
> ```XML
>   <block style="p" paragraphStart="true" chapter="19" initialStartVerse="18" characterId="Jesus" matchesReferenceText="true">
>     <ReferenceBlocks style="p" paragraphStart="true" chapter="19" initialStartVerse="18" characterId="Jesus">
>       <text>« ‹You shall not murder.› ‹You shall not commit adultery.› ‹You shall not steal.› ‹You shall not offer false testimony.›</text>
> ```

Was this intended? I didn't think you were doing this yet. 
And now I think it doesn't match the English file.
___
*[DistFiles/reference_texts/Russian/MRK.xml, line 4249 at r3](https://reviewable.io/reviews/sillsdev/glyssen/722#-MGo5xwi-fbWOwLPO4De:-MGo5xwi-fbWOwLPO4Df:bw678k1) ([raw file](https://github.com/sillsdev/glyssen/blob/a2c133541be4089200632dd1ece34400f62a0baa/DistFiles/reference_texts/Russian/MRK.xml#L4249)):*
> ```XML
>     <ReferenceBlocks style="p" paragraphStart="true" chapter="10" initialStartVerse="19" characterId="Jesus">
>       <verse num="19" />
>       <text>You know the commandments: ‹Do not murder,› ‹Do not commit adultery,› ‹Do not steal,› ‹Do not give false testimony,› ‹Do not defraud,› ‹Honor your father and mother.› »</text>
> ```

Was this intended? I didn't think you were doing this yet. 
And now I think it doesn't match the English file.


<!-- Sent from Reviewable.io -->

2020-09-09 18:48 UTC, tombogle commented
___
*[DistFiles/reference_texts/Russian/LUK.xml, line 8127 at r3](https://reviewable.io/reviews/sillsdev/glyssen/722#-MGo5zSBCoqeg8xdhATA:-MGoBQ0e4NUhPGE4bYEi:b-50ssux) ([raw file](https://github.com/sillsdev/glyssen/blob/a2c133541be4089200632dd1ece34400f62a0baa/DistFiles/reference_texts/Russian/LUK.xml#L8127)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Was this intended? I didn't think you were doing this yet. 
And now I think it doesn't match the English file.
</blockquote></details>

I had done it (now in a separate branch) to see if it worked okay and tried really hard not to let them bleed over into my other cleanup work, but it looks like I failed in 8 places. 


<!-- Sent from Reviewable.io -->

2020-09-09 19:00 UTC, tombogle reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/722)* status: 94 of 100 files reviewed, 5 unresolved discussions (waiting on @andrew-polk)

___
*[DistFiles/reference_texts/English/EXO.xml, line 4264 at r3](https://reviewable.io/reviews/sillsdev/glyssen/722#-MGo5Lou6ScgBl-xvPlt:-MGoB-C4DSO4xZ1ZFg0d:b-896fix) ([raw file](https://github.com/sillsdev/glyssen/blob/a2c133541be4089200632dd1ece34400f62a0baa/DistFiles/reference_texts/English/EXO.xml#L4264)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> off:'
> ```
This one got missed.
</blockquote></details>

Done.
___
*[DistFiles/reference_texts/English/EXO.xml, line 4379 at r3](https://reviewable.io/reviews/sillsdev/glyssen/722#-MGo5RXU3OQwxtwFU7bI:-MGoB0JU2ZUyPfbxVwIY:b-896fix) ([raw file](https://github.com/sillsdev/glyssen/blob/a2c133541be4089200632dd1ece34400f62a0baa/DistFiles/reference_texts/English/EXO.xml#L4379)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> people:'
> ```
Another one missed.
Worth searching for this case?
</blockquote></details>

Done.
___
*[DistFiles/reference_texts/Russian/LUK.xml, line 8127 at r3](https://reviewable.io/reviews/sillsdev/glyssen/722#-MGo5zSBCoqeg8xdhATA:-MGoER-WEF7RCEmqbQ6p:b-896fix) ([raw file](https://github.com/sillsdev/glyssen/blob/a2c133541be4089200632dd1ece34400f62a0baa/DistFiles/reference_texts/Russian/LUK.xml#L8127)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

I had done it (now in a separate branch) to see if it worked okay and tried really hard not to let them bleed over into my other cleanup work, but it looks like I failed in 8 places. 
</blockquote></details>

Done.
___
*[DistFiles/reference_texts/Russian/MAT.xml, line 6300 at r3](https://reviewable.io/reviews/sillsdev/glyssen/722#-MGo5v2V9_4KFeFriQDN:-MGoESnU8goFEdfqa8PQ:b-896fix) ([raw file](https://github.com/sillsdev/glyssen/blob/a2c133541be4089200632dd1ece34400f62a0baa/DistFiles/reference_texts/Russian/MAT.xml#L6300)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Was this intended? I didn't think you were doing this yet. 
And now I think it doesn't match the English file.
</blockquote></details>

Done.
___
*[DistFiles/reference_texts/Russian/MRK.xml, line 4249 at r3](https://reviewable.io/reviews/sillsdev/glyssen/722#-MGo5xwi-fbWOwLPO4De:-MGoETTvCNm_Jczhcuv9:b-896fix) ([raw file](https://github.com/sillsdev/glyssen/blob/a2c133541be4089200632dd1ece34400f62a0baa/DistFiles/reference_texts/Russian/MRK.xml#L4249)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Was this intended? I didn't think you were doing this yet. 
And now I think it doesn't match the English file.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-09 20:55 UTC, andrew-polk approved these changes
> Reviewed 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/722)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-16 15:02 UTC, andrew-polk reviewed
> Reviewed 43 of 43 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/722)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-23 17:56 UTC, andrew-polk reviewed
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/722)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-24 21:30 UTC, andrew-polk reviewed
> Reviewed 50 of 50 files at r7.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/722)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-25 15:02 UTC, andrew-polk reviewed
> Reviewed 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/722)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-30 16:21 UTC, andrew-polk reviewed
> Reviewed 25 of 25 files at r9.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/722)* status: all files reviewed, 2 unresolved discussions (waiting on @tombogle)

___
*[DistFiles/reference_texts/English/1CO.xml, line 100 at r9](https://reviewable.io/reviews/sillsdev/glyssen/722#-MIUnuPb9wr8xreaNLu-:-MIUnuPb9wr8xreaNLu0:b-bas4rl) ([raw file](https://github.com/sillsdev/glyssen/blob/2fe03912832bd63b9465409aec86a8a8afcf4961/DistFiles/reference_texts/English/1CO.xml#L100)):*
> ```XML
>   <block style="p" paragraphStart="true" chapter="1" initialStartVerse="23" characterId="narrator-1CO">
>     <verse num="23" />
>     <text>But we preach Christ crucified; a stumbling block to Jews, and foolishness to Greeks, </text>
> ```

Remind me when we want/need to keep/strip trailing space?
Or is it just that it doesn't matter, so it is easier to just use whatever the DG happens to have?
___
*[DistFiles/reference_texts/English/COL.xml, line 151 at r9](https://reviewable.io/reviews/sillsdev/glyssen/722#-MIUmyND9Hs3lcE74nMY:-MIUmyND9Hs3lcE74nMZ:bmfbzam) ([raw file](https://github.com/sillsdev/glyssen/blob/2fe03912832bd63b9465409aec86a8a8afcf4961/DistFiles/reference_texts/English/COL.xml#L151)):*
> ```
> startVerse="-999"
> ```
I can't remember anything about how these work. Does this look right to you?


<!-- Sent from Reviewable.io -->

2020-10-01 15:12 UTC, andrew-polk reviewed
> Reviewed 10 of 10 files at r10.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/722)* status: all files reviewed, 2 unresolved discussions (waiting on @tombogle)



<!-- Sent from Reviewable.io -->

2020-10-01 20:56 UTC, andrew-polk requested changes
> Reviewed 18 of 18 files at r11.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/722)* status: all files reviewed, 5 unresolved discussions (waiting on @tombogle)

___
*[DistFiles/license.rtf, line 0 at r11](https://reviewable.io/reviews/sillsdev/glyssen/722#-MI_uRqM-yxVm8phWHl9:-MI_uRqM-yxVm8phWHlA:b-qz8iex) ([raw file](https://github.com/sillsdev/glyssen/blob/32d69b8307414b93bdc6f4253b193efc46287789/DistFiles/license.rtf#L0)):*
Likely beyond the scope of this change, but...
we really should get away from rtf to markdown or at least html.
___
*[DistFiles/reference_texts/Russian/ACT.xml, line 3880 at r11](https://reviewable.io/reviews/sillsdev/glyssen/722#-MI_tc6M-wK5_H1Z0pO3:-MI_tc6M-wK5_H1Z0pO4:b7pbkml) ([raw file](https://github.com/sillsdev/glyssen/blob/32d69b8307414b93bdc6f4253b193efc46287789/DistFiles/reference_texts/Russian/ACT.xml#L3880)):*
> ```XML
>     <verse num="27" />
>     <text>В те дни пришли из Иерусалима в Антиохию пророки.</text>
> 	
> ```

Odd extra line with tab...
___
*[DistFiles/reference_texts/Russian/ROM.xml, line 515 at r9](https://reviewable.io/reviews/sillsdev/glyssen/722#-MI_u3lm9lFSDYyaHE0Y:-MI_u3lm9lFSDYyaHE0Z:b-75o9oe) ([raw file](https://github.com/sillsdev/glyssen/blob/2fe03912832bd63b9465409aec86a8a8afcf4961/DistFiles/reference_texts/Russian/ROM.xml#L515)):*
> ```XML
>     </ReferenceBlocks>
>     <verse num="29" />
>     <text>но он еврей, который является одним внутри, и то обрезание, которое в сердце. "Это в духе, не в письме, Его похвала не от людей, но от Бога.</text>
> ```

This deletion looks wrong.


<!-- Sent from Reviewable.io -->

2020-10-02 15:19 UTC, tombogle commented
___
*[DistFiles/license.rtf, line  at r11](https://reviewable.io/reviews/sillsdev/glyssen/722#-MI_uRqM-yxVm8phWHl9:-MIdt2Wd0SC6If4Iuz5n:by0f0b2) ([raw file](https://github.com/sillsdev/glyssen/blob/32d69b8307414b93bdc6f4253b193efc46287789/DistFiles/license.rtf#L)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Likely beyond the scope of this change, but...
we really should get away from rtf to markdown or at least html.
</blockquote></details>

RTF seems to be what WIX supports: https://wixtoolset.org/documentation/manual/v3/bundle/wixstdba/wixstdba_license.html
All the other products I work on also use RTF.


<!-- Sent from Reviewable.io -->

2020-10-02 15:21 UTC, tombogle commented
___
*[DistFiles/reference_texts/English/1CO.xml, line 100 at r9](https://reviewable.io/reviews/sillsdev/glyssen/722#-MIUnuPb9wr8xreaNLu-:-MIdtNcHDLsZ-Xxtc0jP:b-o4waqu) ([raw file](https://github.com/sillsdev/glyssen/blob/2fe03912832bd63b9465409aec86a8a8afcf4961/DistFiles/reference_texts/English/1CO.xml#L100)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Remind me when we want/need to keep/strip trailing space?
Or is it just that it doesn't matter, so it is easier to just use whatever the DG happens to have?
</blockquote></details>

For us, it doesn't really matter. The utility complains about a whitespace difference if the text has an annotation following it and there is no trailing space. Usually I run the comparison in the utility with the "ignore whitespace" box checked, but since I'm trying to carefully ensure we're now in sync with the DG, I cleared that checkbox.


<!-- Sent from Reviewable.io -->

2020-10-02 15:25 UTC, tombogle commented
___
*[DistFiles/reference_texts/English/COL.xml, line 151 at r9](https://reviewable.io/reviews/sillsdev/glyssen/722#-MIUmyND9Hs3lcE74nMY:-MIdtwqd9_cJDSpb7CMU:bef0fi) ([raw file](https://github.com/sillsdev/glyssen/blob/2fe03912832bd63b9465409aec86a8a8afcf4961/DistFiles/reference_texts/English/COL.xml#L151)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> startVerse="-999"
> ```
I can't remember anything about how these work. Does this look right to you?
</blockquote></details>

kNonSpecificStartOrStop = -999 . I looked at the code for a few minutes and concluded that it must have made sense to one of us at some time in the past.


<!-- Sent from Reviewable.io -->

2020-10-02 15:25 UTC, tombogle commented
___
*[DistFiles/reference_texts/English/COL.xml, line 151 at r9](https://reviewable.io/reviews/sillsdev/glyssen/722#-MIUmyND9Hs3lcE74nMY:-MIdumpk0YpZ9bhesz0P:bm387xj) ([raw file](https://github.com/sillsdev/glyssen/blob/2fe03912832bd63b9465409aec86a8a8afcf4961/DistFiles/reference_texts/English/COL.xml#L151)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

kNonSpecificStartOrStop = -999 . I looked at the code for a few minutes and concluded that it must have made sense to one of us at some time in the past.
</blockquote></details>

At least it helps us get in touch with our inner COBOL programmer.


<!-- Sent from Reviewable.io -->

2020-10-02 15:38 UTC, tombogle reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/722)* status: all files reviewed, 5 unresolved discussions (waiting on @andrew-polk)

___
*[DistFiles/reference_texts/Russian/ACT.xml, line 3880 at r11](https://reviewable.io/reviews/sillsdev/glyssen/722#-MI_tc6M-wK5_H1Z0pO3:-MIdvAQ31URPtcd9cYFG:b-896fix) ([raw file](https://github.com/sillsdev/glyssen/blob/32d69b8307414b93bdc6f4253b193efc46287789/DistFiles/reference_texts/Russian/ACT.xml#L3880)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Odd extra line with tab...
</blockquote></details>

Done.
___
*[DistFiles/reference_texts/Russian/ROM.xml, line 515 at r9](https://reviewable.io/reviews/sillsdev/glyssen/722#-MI_u3lm9lFSDYyaHE0Y:-MIdxfRv6HkGLxD6GtFg:b-896fix) ([raw file](https://github.com/sillsdev/glyssen/blob/2fe03912832bd63b9465409aec86a8a8afcf4961/DistFiles/reference_texts/Russian/ROM.xml#L515)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This deletion looks wrong.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-02 19:33 UTC, andrew-polk requested changes
> Reviewed 2 of 2 files at r12.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/722)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @tombogle)

___
*[DistFiles/reference_texts/Russian/ROM.xml, line 515 at r9](https://reviewable.io/reviews/sillsdev/glyssen/722#-MI_u3lm9lFSDYyaHE0Y:-MIenC5a9POOGApvLM4x:bz4l504) ([raw file](https://github.com/sillsdev/glyssen/blob/2fe03912832bd63b9465409aec86a8a8afcf4961/DistFiles/reference_texts/Russian/ROM.xml#L515)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Pretty sure it doesn't matter, but we ended up with an indention change on this line.


<!-- Sent from Reviewable.io -->

2020-10-02 19:33 UTC, andrew-polk approved these changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/722)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-02 20:32 UTC, merged