PG-1436: Changed when UpdateFollowingContinuationBlocks gets called
sillsdev/Glyssen pull request #776
Opened 2021-03-29 19:49 UTC by tombogle

when applying the correlated blocks of a BlockMatchup to ensure preceding blocks are in a valid state. This avoids an exception caused by calling it prematurely before trailing narrator blocks have their MultiBlockQuote property set to None.
 Note: issue is duplicated by: PG-1437 and PG-1438.

2021-03-29 22:50 UTC, andrew-polk approved these changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/776)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tombogle)



<!-- Sent from Reviewable.io -->

2021-03-29 22:50 UTC, andrew-polk requested changes
Possible to feasibly unit test?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/776#-:-MX-AeWwB_hH0jX6q0dV:b-rfhb5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tombogle)



<!-- Sent from Reviewable.io -->

2021-03-30 02:53 UTC, tombogle commented
There is already an existing unit test that covers this. I checked to be sure that it broke when I removed the call to UpdateFollowingContinuationBlocks and that changing the logic in Apply fixed it.





<!-- Sent from Reviewable.io -->

2021-03-30 15:51 UTC, andrew-polk approved these changes

2021-03-30 16:00 UTC, merged