PG-1487: Support for DBL metadata version 2.2.1 and USX 3.0
sillsdev/Glyssen pull request #835
Opened 2022-09-01 20:11 UTC by tombogle

2022-09-01 20:11 UTC, tombogle commented
Solves https://jira.sil.org/browse/PG-1487

2022-09-02 13:33 UTC, ermshiperete requested changes

2022-09-02 13:33 UTC, ermshiperete commented on GlyssenSharedTests/app.config
> +        <bindingRedirect oldVersion="0.0.0.0-10.1.0.0" newVersion="10.1.0.0" />
Shouldn't this be 11.0.0.0?

2022-09-02 13:53 UTC, tombogle commented
*[`GlyssenSharedTests/app.config` line 7 at r1](https://reviewable.io/reviews/sillsdev/glyssen/835#-NAuf_XTqWoQGaJqxobm-r1-7:-NAyT_Ol4eSJPZhmUmAN:b-gex83o) ([raw file](https://github.com/sillsdev/glyssen/blob/cdc9e29c4a3d1aec58af7dc0ad1e2e7f491fb2d3/GlyssenSharedTests/app.config#L7)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

Shouldn't this be 11.0.0.0?
</blockquote></details>

These binding redirects don't appear to be necessary at all.


<!-- Sent from Reviewable.io -->

2022-09-02 14:06 UTC, ermshiperete approved these changes

2022-09-02 14:13 UTC, merged