PTX-22920: Reverted the changes from Normal, Dialogue, and Quotation to Implicit
sillsdev/Glyssen pull request #848
Opened 2023-02-08 20:28 UTC by tombogle

We realized that the change to mark so many verses as Implicit did not really reflect the intention of that type, and actually made it harder for a user distinguish between normal and implicit for the purpose of deciding when it was appropriate to use quotation marks.
Also marked a couple longer discourses in GEN (ch 24 & ch 44) as Implicit.

2023-02-08 21:16 UTC, andrew-polk requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/Glyssen/848)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)

___
*[`GlyssenCharacters/Resources/CharacterVerse.txt` line 338 at r1](https://reviewable.io/reviews/sillsdev/Glyssen/848#-NNmrjUf-JdF34avWV7b:-NNmrjUf-JdF34avWV7c:b-prxtoc) ([raw file](https://github.com/sillsdev/Glyssen/blob/16bbaf1417e141c2ac384919ec0390907870ed0c/GlyssenCharacters/Resources/CharacterVerse.txt#L338)):*
> ```help
> GEN	24	47	Abraham's chief servant			ImplicitWithPotentialSelfQuote			
> GEN	24	48	Abraham's chief servant			ImplicitWithPotentialSelfQuote			
> GEN	24	49	Abraham's chief servant			Implicit			
> ```

I thought (by logic and the code in the test) that all these lines should be EntireVerse.

Also in Gen 44


<!-- Sent from Reviewable.io -->

2023-02-09 13:41 UTC, tombogle commented
*[`GlyssenCharacters/Resources/CharacterVerse.txt` line 338 at r1](https://reviewable.io/reviews/sillsdev/Glyssen/848#-NNmrjUf-JdF34avWV7b:-NNqORhD0t3auDed4Yng:bdvop2d) ([raw file](https://github.com/sillsdev/Glyssen/blob/16bbaf1417e141c2ac384919ec0390907870ed0c/GlyssenCharacters/Resources/CharacterVerse.txt#L338)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I thought (by logic and the code in the test) that all these lines should be EntireVerse.

Also in Gen 44
</blockquote></details>

It would be harmless to mark them as EntireVerse, but it would be redundant. Implicit implies EntireVerse. So if I change these newly-added ones, for consistency I should also have to go and add EntireVerse to all the other Implicit entries. That would actually (very slightly) simplify the check in Paratext, which currently has to look at both the quote type and the quote position. So maybe it's worth it. What do you think?


<!-- Sent from Reviewable.io -->

2023-02-09 13:46 UTC, tombogle commented
*[`GlyssenCharacters/Resources/CharacterVerse.txt` line 338 at r1](https://reviewable.io/reviews/sillsdev/Glyssen/848#-NNmrjUf-JdF34avWV7b:-NNqQ-l75UbcD7K7ALLq:b-75kvfv) ([raw file](https://github.com/sillsdev/Glyssen/blob/16bbaf1417e141c2ac384919ec0390907870ed0c/GlyssenCharacters/Resources/CharacterVerse.txt#L338)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

It would be harmless to mark them as EntireVerse, but it would be redundant. Implicit implies EntireVerse. So if I change these newly-added ones, for consistency I should also have to go and add EntireVerse to all the other Implicit entries. That would actually (very slightly) simplify the check in Paratext, which currently has to look at both the quote type and the quote position. So maybe it's worth it. What do you think?
</blockquote></details>

I do see that for ImplicitWithPotentialSelfQuote, I coded the updater such that it is already inconsistent. Sometimes those entries have EntireVerse and sometimes not. I think I'll go ahead and make it add that for all of them.


<!-- Sent from Reviewable.io -->

2023-02-09 15:49 UTC, andrew-polk approved these changes

2023-02-09 15:49 UTC, andrew-polk requested changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/848)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)

___
*[`GlyssenCharacters/Resources/CharacterVerse.txt` line 1 at r2](https://reviewable.io/reviews/sillsdev/glyssen/848#-NNqqZpR7XJe_Z7ZhCLF:-NNqqZpX4bkcjCq03iWP:b-j1mrtb) ([raw file](https://github.com/sillsdev/glyssen/blob/e45ae5e3aa4fd245a5e6a8ce7a21b9d05c9f24f6/GlyssenCharacters/Resources/CharacterVerse.txt#L1)):*
> ```help
> Control File Version	169
> ```

Reviewable thinks every line 


<!-- Sent from Reviewable.io -->

2023-02-09 15:50 UTC, andrew-polk approved these changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/848)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tombogle)



<!-- Sent from Reviewable.io -->

2023-02-09 15:54 UTC, merged